; This file is automatically generated. Please don't change it manually 
	section	compressed,text 
	global rlh_car0  
rlh_car0:  
	incbin "rlh/car0.rlh"  
	global rlh_car1  
rlh_car1:  
	incbin "rlh/car1.rlh"  
	global rlh_circuit_daytono  
rlh_circuit_daytono:  
	incbin "rlh/circuit_daytono.rlh"  
	global rlh_circuit_frame  
rlh_circuit_frame:  
	incbin "rlh/circuit_frame.rlh"  
	global rlh_circuit_holiday_on_ice  
rlh_circuit_holiday_on_ice:  
	incbin "rlh/circuit_holiday_on_ice.rlh"  
	global rlh_circuit_monaco  
rlh_circuit_monaco:  
	incbin "rlh/circuit_monaco.rlh"  
	global rlh_circuit_monzarella  
rlh_circuit_monzarella:  
	incbin "rlh/circuit_monzarella.rlh"  
	global rlh_circuit_take_it_easy  
rlh_circuit_take_it_easy:  
	incbin "rlh/circuit_take_it_easy.rlh"  
	global rlh_circuit_tiles_0  
rlh_circuit_tiles_0:  
	incbin "rlh/circuit_tiles_0.rlh"  
	global rlh_circuit_tiles_1  
rlh_circuit_tiles_1:  
	incbin "rlh/circuit_tiles_1.rlh"  
	global rlh_circuit_tiles_2  
rlh_circuit_tiles_2:  
	incbin "rlh/circuit_tiles_2.rlh"  
	global rlh_circuit_you_turn  
rlh_circuit_you_turn:  
	incbin "rlh/circuit_you_turn.rlh"  
	global rlh_hdd  
rlh_hdd:  
	incbin "rlh/hdd.rlh"  
	global rlh_hud  
rlh_hud:  
	incbin "rlh/hud.rlh"  
	global rlh_intro_0  
rlh_intro_0:  
	incbin "rlh/intro_0.rlh"  
	global rlh_intro_helmet_a  
rlh_intro_helmet_a:  
	incbin "rlh/intro_helmet_a.rlh"  
	global rlh_intro_helmet_b  
rlh_intro_helmet_b:  
	incbin "rlh/intro_helmet_b.rlh"  
	global rlh_intro_helmet_c  
rlh_intro_helmet_c:  
	incbin "rlh/intro_helmet_c.rlh"  
	global rlh_introscreen  
rlh_introscreen:  
	incbin "rlh/introscreen.rlh"  
	global rlh_round_borders  
rlh_round_borders:  
	incbin "rlh/round_borders.rlh"  
	global rlh_you_loose  
rlh_you_loose:  
	incbin "rlh/you_loose.rlh"  
	global rlh_you_win  
rlh_you_win:  
	incbin "rlh/you_win.rlh"  
