; This file is automatically generated. Please don't change it manually 
	section	compressed,text 
	global huf_car0  
huf_car0:  
	incbin "huf/car0.huf"  
	global huf_car1  
huf_car1:  
	incbin "huf/car1.huf"  
	global huf_circuit_tiles_0  
huf_circuit_tiles_0:  
	incbin "huf/circuit_tiles_0.huf"  
	global huf_circuitdata  
huf_circuitdata:  
	incbin "huf/circuitdata.huf"  
	global huf_intro0a  
huf_intro0a:  
	incbin "huf/intro0a.huf"  
	global huf_intro0b  
huf_intro0b:  
	incbin "huf/intro0b.huf"  
	global huf_intro0c  
huf_intro0c:  
	incbin "huf/intro0c.huf"  
	global huf_introscreen  
huf_introscreen:  
	incbin "huf/introscreen.huf"  
	global huf_smallfont  
huf_smallfont:  
	incbin "huf/smallfont.huf"  
