; This file is automatically generated. Please don't change it manually 
	section	compressed,text 
	global huf_car0  
huf_car0:  
	incbin "huf/car0.huf"  
	global huf_car1  
huf_car1:  
	incbin "huf/car1.huf"  
	global huf_circuit_tiles_0  
huf_circuit_tiles_0:  
	incbin "huf/circuit_tiles_0.huf"  
	global huf_circuitdata  
huf_circuitdata:  
	incbin "huf/circuitdata.huf"  
	global huf_intro_0  
huf_intro_0:  
	incbin "huf/intro_0.huf"  
	global huf_intro_helmet_a  
huf_intro_helmet_a:  
	incbin "huf/intro_helmet_a.huf"  
	global huf_intro_helmet_b  
huf_intro_helmet_b:  
	incbin "huf/intro_helmet_b.huf"  
	global huf_intro_helmet_c  
huf_intro_helmet_c:  
	incbin "huf/intro_helmet_c.huf"  
	global huf_introscreen  
huf_introscreen:  
	incbin "huf/introscreen.huf"  
	global huf_smallfont  
huf_smallfont:  
	incbin "huf/smallfont.huf"  
