# Debug
DEBUG = 0
JOYSTICK = 1

# Path
MAME_SAVESTATE_PATH = C:\MameNew\sta\phc25
TO_COMPRESS_PATH = res_to_compress
TO_EXTRACT = bmp_to_extract
TO_EXTRACT_AND_COMPRESS_PATH = bmp_to_extract_and_compress
TO_EXTRACT_AND_COMPRESS_COLOR_PATH = color_bmp_to_extract_and_compress
BMP_TO_EXTRACT_PATH = bmp_to_extract
RESOURCES_RAW = res_raw
OUTPUT_PATH = .
PRECOMP_PATH = precomp
COMPRESSION_PATH = rlh
TOOLS_PATH = tools
OBJ_PATH = obj
INC_PATH = inc

# Tools
AS="$(TOOLS_PATH)/vasmz80_mot_win32.exe"
LD="$(TOOLS_PATH)/vlink.exe"
INJECT=dotnet $(TOOLS_PATH)/InjectPhcInSaveState.dll
HUFF80=dotnet $(TOOLS_PATH)/HuffmanZ80.dll
APPLY_PHC_MASK=dotnet $(TOOLS_PATH)/ApplyPhcFileBitMask.dll
EXTRACT_RAW_IMAGE_DATA=dotnet $(TOOLS_PATH)/ExtractRawImageData.dll
EXTRACT_COLOR_IMAGE_DATA=dotnet $(TOOLS_PATH)/Extract2BitColorImage.dll

# Assembler flags
ASFLAGS=-chklabels -nocase -Fvobj -Dvasm=1 -quiet
LDFLAGS=-brawbin1 -Tmain.ld

# Target and intermediate files
TARGET=turbo.phc
SAVESTATE=turbo.sta
STUFFING_SAVESTATE=stuffing.sta
SECTION_MAP_FILE=sectionmap.txt
RLH_COMPRESSOR_SOURCE_FILE=_rlh_decomp.s
COMPRESSED_FILES_INCLUDER=_compressedfiles.s

# Makefile targets definition
OBJ = $(patsubst %.s,$(OBJ_PATH)/%.o,$(wildcard *.s))
INC = $(wildcard $(INC_PATH)/*.inc)

# Compressed files management
TO_COMPRESS_ALL = $(wildcard $(TO_COMPRESS_PATH)/*)
TO_COMPRESS_BMP = $(wildcard $(TO_COMPRESS_PATH)/*.bmp)
TO_COMPRESS_OTHER = $(filter-out %.bmp,$(TO_COMPRESS_ALL))
GENERATED_RESOURCE_CODE_FILE = $(COMPRESSED_FILES_INCLUDER)
TO_EXTRACT_BMP = $(wildcard $(BMP_TO_EXTRACT_PATH)/*.bmp)
EXTRACTED_BMP = $(patsubst $(BMP_TO_EXTRACT_PATH)/%.bmp,$(RESOURCES_RAW)/%.raw,$(TO_EXTRACT_BMP))
TO_EXTRACT_AND_COMPRESS_BMP = $(wildcard $(TO_EXTRACT_AND_COMPRESS_PATH)/*.bmp)
EXTRACTED_TO_COMPRESS = $(patsubst $(TO_EXTRACT_AND_COMPRESS_PATH)/%.bmp,$(TO_COMPRESS_PATH)/%.raw,$(TO_EXTRACT_AND_COMPRESS_BMP))
COLOR_IMAGES_BMP = $(wildcard $(TO_EXTRACT_AND_COMPRESS_COLOR_PATH)/*.bmp)
COLOR_IMAGES_RAW = $(patsubst $(TO_EXTRACT_AND_COMPRESS_COLOR_PATH)/%.bmp,$(TO_COMPRESS_PATH)/%.raw,$(COLOR_IMAGES_BMP))

define RESOURCE_FILE_TEMPLATE
echo 	global rlh_$(basename $(FILE)) >> $(GENERATED_RESOURCE_CODE_FILE) &
echo rlh_$(basename $(FILE)): >> $(GENERATED_RESOURCE_CODE_FILE) &
echo 	incbin "$(COMPRESSION_PATH)/$(basename $(FILE)).rlh" >> $(GENERATED_RESOURCE_CODE_FILE) &
endef

define COLOR_IMAGES_RAW_EXTRACTION_TEMPLATE
$(TO_COMPRESS_PATH)/$(1).raw: $(TO_EXTRACT_AND_COMPRESS_COLOR_PATH)/$(1).bmp
	$(EXTRACT_COLOR_IMAGE_DATA) $$< $$@
endef

all:
	make sta

phc:
	make $(OUTPUT_PATH)/$(TARGET)

sta:
	make $(OUTPUT_PATH)/$(SAVESTATE)

rebuild:
	make clean
	make all

$(TO_COMPRESS_PATH)/circuitdata.bin: circuitdata.data
	$(AS) circuitdata.data -Fbin -o $(TO_COMPRESS_PATH)/circuitdata.bin -quiet

$(OBJ_PATH)/textwrite.o: res_raw/smallfont.raw

$(TO_COMPRESS_PATH)/%.raw: $(TO_EXTRACT_AND_COMPRESS_PATH)/%.bmp
	$(EXTRACT_RAW_IMAGE_DATA) $< $@

$(RESOURCES_RAW)/%.raw: $(BMP_TO_EXTRACT_PATH)/%.bmp $(RESOURCES_RAW)
	$(EXTRACT_RAW_IMAGE_DATA) $< $@

$(foreach file,$(notdir $(basename $(COLOR_IMAGES_RAW))),$(eval $(call COLOR_IMAGES_RAW_EXTRACTION_TEMPLATE,$(file))))

$(OUTPUT_PATH)/$(SAVESTATE): $(OUTPUT_PATH)/$(TARGET) $(STUFFING_SAVESTATE)
	$(INJECT) $(STUFFING_SAVESTATE) $(OUTPUT_PATH)/$(TARGET) $(OUTPUT_PATH)/$(SAVESTATE)
	copy $(OUTPUT_PATH)\$(SAVESTATE) $(MAME_SAVESTATE_PATH)

$(OUTPUT_PATH)/$(TARGET): $(OUTPUT_PATH) $(OBJ_PATH) $(OBJ) main.ld
	$(LD) $(LDFLAGS) -o $(OUTPUT_PATH)/$(TARGET) $(OBJ) -M > $(SECTION_MAP_FILE)
	$(APPLY_PHC_MASK) $(OUTPUT_PATH)/$(TARGET) $(OUTPUT_PATH)/$(SECTION_MAP_FILE)

$(COMPRESSED_FILES_INCLUDER): $(EXTRACTED_TO_COMPRESS) $(TO_COMPRESS_PATH)/circuitdata.bin $(COLOR_IMAGES_BMP) $(COLOR_IMAGES_RAW)

$(OBJ_PATH)/%.o: %.s $(INC) $(PRECOMP_PATH)
	$(AS) $(ASFLAGS) -L $(PRECOMP_PATH)/$<.txt -o $@ $< -DDEBUG=$(DEBUG) -DJOYSTICK=$(JOYSTICK)

$(RLH_COMPRESSOR_SOURCE_FILE) $(COMPRESSED_FILES_INCLUDER) $(COMPRESSED): $(TO_COMPRESS_ALL) $(COMPRESSION_PATH) $(TO_COMPRESS_PATH) $(COLOR_IMAGES_RAW)
	$(HUFF80) $(foreach file,$(notdir $(TO_COMPRESS_BMP)),$(TO_COMPRESS_PATH)/$(basename $(file)).bmp,$(COMPRESSION_PATH)/$(basename $(file)).rlh,62) $(foreach file,$(notdir $(TO_COMPRESS_OTHER)),$(TO_COMPRESS_PATH)/$(file),$(COMPRESSION_PATH)/$(basename $(file)).rlh) $(RLH_COMPRESSOR_SOURCE_FILE)
	echo ; This file is automatically generated. Please don't change it manually > $(GENERATED_RESOURCE_CODE_FILE)
	echo 	section	compressed,text >> $(GENERATED_RESOURCE_CODE_FILE)
	$(foreach FILE,$(notdir $(TO_COMPRESS_ALL)),$(RESOURCE_FILE_TEMPLATE))

# Directories creation
$(COMPRESSION_PATH):
	mkdir $(COMPRESSION_PATH)

$(OUTPUT_PATH):
	mkdir $(OUTPUT_PATH)

$(OBJ_PATH):
	mkdir $(OBJ_PATH)

$(PRECOMP_PATH):
	mkdir $(PRECOMP_PATH)

$(TO_COMPRESS_PATH):
	mkdir $(TO_COMPRESS_PATH)

$(RESOURCES_RAW):
	mkdir $(RESOURCES_RAW)

clean:
ifneq ($(wildcard $(COMPRESSION_PATH)),)
	rmdir /S /Q $(COMPRESSION_PATH)
endif
ifneq ($(wildcard $(PRECOMP_PATH)),)
	rmdir /S /Q $(PRECOMP_PATH)
endif
ifneq ($(wildcard $(OBJ_PATH)),)
	rmdir /S /Q $(OBJ_PATH)
endif
ifneq ($(wildcard $(SECTION_MAP_FILE)),)
	del $(SECTION_MAP_FILE)
endif
ifneq ($(wildcard $(TARGET)),)
	del $(TARGET)
endif
ifneq ($(wildcard $(SAVESTATE)),)
	del $(SAVESTATE)
endif
	cd $(TO_COMPRESS_PATH) & $(foreach FILE,$(EXTRACTED_TO_COMPRESS),del $(notdir $(FILE)) &)
	cd $(TO_COMPRESS_PATH) & $(foreach FILE,$(COLOR_IMAGES_RAW),del $(notdir $(FILE)) &)
	cd $(TO_COMPRESS_PATH) & del circuitdata.bin
	cd $(RESOURCES_RAW) & del smallfont.raw
