# Debug
DEBUG = 0

# Path
TO_COMPRESS_PATH = res_to_compress
TO_EXTRACT_AND_COMPRESS_PATH = bmp_to_extract_and_compress
TO_EXTRACT_AND_COMPRESS_COLOR_PATH = color_bmp_to_extract_and_compress
BMP_TO_EXTRACT_PATH = bmp_to_extract
RESOURCES_PATH = res
OUTPUT_PATH = .
PRECOMP_PATH = precomp
HUFFMAN_PATH = huf
TOOLS_PATH = tools
OBJ_PATH = obj
INC_PATH = inc

# Tools
AS="$(TOOLS_PATH)/vasmz80_mot_win32.exe"
LD="$(TOOLS_PATH)/vlink.exe"
INJECT=dotnet $(TOOLS_PATH)/InjectPhcInSaveState.dll
HUFF80=dotnet $(TOOLS_PATH)/HuffmanZ80.dll
APPLY_PHC_MASK=dotnet $(TOOLS_PATH)/ApplyPhcFileBitMask.dll
EXTRACT_RAW_IMAGE_DATA=dotnet $(TOOLS_PATH)/ExtractRawImageData.dll
EXTRACT_COLOR_IMAGE_DATA=dotnet $(TOOLS_PATH)/Extract2BitColorImage.dll

# Assembler flags
ASFLAGS=-chklabels -nocase -Fvobj -Dvasm=1 -quiet
LDFLAGS=-brawbin1 -Tmain.ld

# Target and intermediate files
TARGET=turbo.phc
SAVESTATE=turbo.sta
STUFFING_SAVESTATE=stuffing.sta
SECTION_MAP_FILE=sectionmap.txt
HUFFMAN_COMPRESSOR_SOURCE_FILE=_huff_decomp.s
COMPRESSED_FILES_INCLUDER=_compressedfiles.s

# Makefile targets definition
OBJ = $(patsubst %.s,$(OBJ_PATH)/%.o,$(wildcard *.s))
INC = $(wildcard $(INC_PATH)/*.inc)

# Compressed files management
TO_COMPRESS_ALL = $(wildcard $(TO_COMPRESS_PATH)/*)
TO_COMPRESS_BMP = $(wildcard $(TO_COMPRESS_PATH)/*.bmp)
TO_COMPRESS_OTHER = $(filter-out %.bmp,$(TO_COMPRESS_ALL))
GENERATED_RESOURCE_CODE_FILE = $(COMPRESSED_FILES_INCLUDER)
TO_EXTRACT_AND_COMPRESS_BMP = $(wildcard $(TO_EXTRACT_AND_COMPRESS_PATH)/*.bmp)
EXTRACTED_TO_COMPRESS = $(patsubst $(TO_EXTRACT_AND_COMPRESS_PATH)/%.bmp,$(TO_COMPRESS_PATH)/%.raw,$(TO_EXTRACT_AND_COMPRESS_BMP))
INTRO_SCREENS_RAW = $(TO_COMPRESS_PATH)/introscreen.raw $(TO_COMPRESS_PATH)/intro0a.raw $(TO_COMPRESS_PATH)/intro0b.raw $(TO_COMPRESS_PATH)/intro0c.raw

define RESOURCE_FILE_TEMPLATE
echo 	global huf_$(basename $(FILE)) >> $(GENERATED_RESOURCE_CODE_FILE) &
echo huf_$(basename $(FILE)): >> $(GENERATED_RESOURCE_CODE_FILE) &
echo 	incbin "$(HUFFMAN_PATH)/$(basename $(FILE)).huf" >> $(GENERATED_RESOURCE_CODE_FILE) &
endef

all:
	make sta

phc:
	make $(OUTPUT_PATH)/$(TARGET)

sta:
	make $(OUTPUT_PATH)/$(SAVESTATE)

rebuild:
	make clean
	make all

$(TO_COMPRESS_PATH)/circuitdata.bin: circuitdata.data
	$(AS) circuitdata.data -Fbin -o $(TO_COMPRESS_PATH)/circuitdata.bin -quiet 

$(TO_COMPRESS_PATH)/introscreen.raw: $(TO_EXTRACT_AND_COMPRESS_COLOR_PATH)/introscreen.bmp
	$(EXTRACT_COLOR_IMAGE_DATA) $(TO_EXTRACT_AND_COMPRESS_COLOR_PATH)/introscreen.bmp $(TO_COMPRESS_PATH)/introscreen.raw
$(TO_COMPRESS_PATH)/intro0a.raw: $(TO_EXTRACT_AND_COMPRESS_COLOR_PATH)/intro0a.bmp
	$(EXTRACT_COLOR_IMAGE_DATA) $(TO_EXTRACT_AND_COMPRESS_COLOR_PATH)/intro0a.bmp $(TO_COMPRESS_PATH)/intro0a.raw
$(TO_COMPRESS_PATH)/intro0b.raw: $(TO_EXTRACT_AND_COMPRESS_COLOR_PATH)/intro0b.bmp
	$(EXTRACT_COLOR_IMAGE_DATA) $(TO_EXTRACT_AND_COMPRESS_COLOR_PATH)/intro0b.bmp $(TO_COMPRESS_PATH)/intro0b.raw
$(TO_COMPRESS_PATH)/intro0c.raw: $(TO_EXTRACT_AND_COMPRESS_COLOR_PATH)/intro0c.bmp
	$(EXTRACT_COLOR_IMAGE_DATA) $(TO_EXTRACT_AND_COMPRESS_COLOR_PATH)/intro0c.bmp $(TO_COMPRESS_PATH)/intro0c.raw

$(RESOURCES_PATH)/%.raw: $(BMP_TO_EXTRACT_PATH)/%.bmp
	$(EXTRACT_RAW_IMAGE_DATA) $< $@

$(OUTPUT_PATH)/$(SAVESTATE): $(OUTPUT_PATH)/$(TARGET) $(STUFFING_SAVESTATE)
	$(INJECT) $(STUFFING_SAVESTATE) $(OUTPUT_PATH)/$(TARGET) $(OUTPUT_PATH)/$(SAVESTATE)
#Pas bien, ca:
	copy $(OUTPUT_PATH)\$(SAVESTATE) C:\MameNew\sta\phc25\

$(OUTPUT_PATH)/$(TARGET): $(OUTPUT_PATH) $(OBJ_PATH) $(OBJ) main.ld
	$(LD) $(LDFLAGS) -o $(OUTPUT_PATH)/$(TARGET) $(OBJ) -M > $(SECTION_MAP_FILE)
	$(APPLY_PHC_MASK) $(OUTPUT_PATH)/$(TARGET) $(OUTPUT_PATH)/$(SECTION_MAP_FILE)

$(TO_COMPRESS_PATH)/%.raw: $(TO_EXTRACT_AND_COMPRESS_PATH)/%.bmp
	$(EXTRACT_RAW_IMAGE_DATA) $< $@

$(COMPRESSED_FILES_INCLUDER): $(EXTRACTED_TO_COMPRESS) $(TO_COMPRESS_PATH)/circuitdata.bin $(INTRO_SCREENS_RAW)

$(OBJ_PATH)/%.o: %.s $(INC) $(PRECOMP_PATH)
	$(AS) $(ASFLAGS) -L $(PRECOMP_PATH)/$<.txt -o $@ $< -DDEBUG=$(DEBUG)

$(HUFFMAN_COMPRESSOR_SOURCE_FILE) $(COMPRESSED_FILES_INCLUDER) $(COMPRESSED): $(TO_COMPRESS_ALL) $(HUFFMAN_PATH) $(TO_COMPRESS_PATH) $(INTRO_SCREENS_RAW)
	$(HUFF80) $(foreach file,$(notdir $(TO_COMPRESS_BMP)),$(TO_COMPRESS_PATH)/$(basename $(file)).bmp,$(HUFFMAN_PATH)/$(basename $(file)).huf,62) $(foreach file,$(notdir $(TO_COMPRESS_OTHER)),$(TO_COMPRESS_PATH)/$(file),$(HUFFMAN_PATH)/$(basename $(file)).huf) $(HUFFMAN_COMPRESSOR_SOURCE_FILE)
	echo ; This file is automatically generated. Please don't change it manually > $(GENERATED_RESOURCE_CODE_FILE)
	echo 	section	compressed,text >> $(GENERATED_RESOURCE_CODE_FILE)
	$(foreach FILE,$(notdir $(TO_COMPRESS_ALL)),$(RESOURCE_FILE_TEMPLATE))

# Directories creation
$(HUFFMAN_PATH):
	mkdir $(HUFFMAN_PATH)

$(OUTPUT_PATH):
	mkdir $(OUTPUT_PATH)

$(OBJ_PATH):
	mkdir $(OBJ_PATH)

$(PRECOMP_PATH):
	mkdir $(PRECOMP_PATH)

$(RESOURCES_PATH):
	mkdir $(RESOURCES_PATH)

$(TO_COMPRESS_PATH):
	mkdir $(TO_COMPRESS_PATH)


clean:
ifneq ($(wildcard $(HUFFMAN_PATH)),)
	rmdir /S /Q $(HUFFMAN_PATH)
endif
ifneq ($(wildcard $(PRECOMP_PATH)),)
	rmdir /S /Q $(PRECOMP_PATH)
endif
ifneq ($(wildcard $(OBJ_PATH)),)
	rmdir /S /Q $(OBJ_PATH)
endif
ifneq ($(wildcard $(SECTION_MAP_FILE)),)
	del $(SECTION_MAP_FILE)
endif
ifneq ($(wildcard $(TARGET)),)
	del $(TARGET)
endif
ifneq ($(wildcard $(SAVESTATE)),)
	del $(SAVESTATE)
endif
	cd $(TO_COMPRESS_PATH) & $(foreach FILE,$(EXTRACTED_TO_COMPRESS),del $(notdir $(FILE)) &)
	cd $(TO_COMPRESS_PATH) & del circuitdata.bin
	cd $(TO_COMPRESS_PATH) & del introscreen.raw & del intro0a.raw & del intro0b.raw & del intro0c.raw
